name: 'Delete old artifacts'
on:
  workflow_dispatch:
    inputs:
      expireIn:
        description: 'Prune artifacts older than'
        required: true
        default: '7 days'
  schedule:
    - cron: '0 * * * *' # every hour

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "expire-in: ${{ github.event.inputs.expireIn }}"
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          expire-in: ${{ github.event.inputs.expireIn }}
